SELECT COUNT( *)
FROM crime_boston;

SELECT YEAR
FROM crime_boston
GROUP BY YEAR;

SELECT COUNT( DISTINCT OFFENSE_CODE)
FROM crime_boston;

SELECT COUNT( DISTINCT  DISTRICT)
FROM crime_boston;

SELECT OFFENSE_CODE_GROUP, COUNT(*) AS count
FROM crime_boston
GROUP BY OFFENSE_CODE_GROUP
ORDER BY COUNT DESC LIMIT 1;

SELECT STREET, COUNT(*)  AS COUNT
FROM crime_boston 
WHERE OFFENSE_CODE_GROUP = 'Motor Vehicle Accident Response'
GROUP BY STREET
ORDER BY COUNT DESC LIMIT 5;